@startuml

'
'DOC Icons Azure
'https://github.com/plantuml-stdlib/Azure-PlantUML

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/python.puml
!include DEVICONS/mongodb.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-1/dist/AzureCommon.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Databases/AzureRedisCache.puml
!includeurl AzurePuml/Databases/AzureSqlDatabase.puml
!includeurl AzurePuml/InternetOfThings/AzureIoTHub.puml
!includeurl AzurePuml/Web/AzureCDN.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Identity/AzureActiveDirectoryB2C.puml
!includeurl AzurePuml/Mobile/AzureNotificationHubs.puml

LAYOUT_WITH_LEGEND()
Person(cliente, "Cliente", "cliente logado na aplicacao", "users")
System(pwa, "PWA", "external", "angular")

AzureActiveDirectoryB2C(azureAd, "Autenticação", "B2C")
Rel_L(pwa, azureAd, " ")

Enterprise_Boundary(privado, "privado") {
   AzureWebApp(api, "API Rest", "pool de api's")

   AzureRedisCache(redis, "Cache", "Redis")
   Rel_L(api, redis, " ")

   System_Boundary(catalogo1, "Catalogo - boundery context") { 
    AzureWebApp(catalogo2, "Catalogo", "API")
    AzureCosmosDb(catalogo3, "NoSql", "CosmosDB")
    AzureCDN(catalogo4, "CDN", "Azure CDN")
    Rel_D(catalogo2, catalogo3, "tcp")
    Rel_L(catalogo4, catalogo3, "https")
   }

   System_Boundary(ecm1, "ECM - Engine Control Module - boundery context") { 
     AzureWebApp(ecm2, "ECM - Engine Control Module", "API")
     AzureCosmosDb(ecm3, "ECM - Engine Control Module", "CosmosDb")
     Rel_R(ecm2, ecm3, "tcp")

     AzureIoTHub(ecm4, "IoT", "Azure IoT Hub")    
     Rel(ecm2, ecm4, " ") 
   }

   System_Boundary(pagamento1, "Pagamento - boundery context") { 
    AzureWebApp(pagamento2, "Gateway pagamento", "API")
    AzureSqlDatabase(pagamento3, "Database", "Sql Server")
    Rel_D(pagamento2, pagamento3, " ")
   }

   System_Boundary(checkinCheckout, "Check-in / Check-out - boundery context") { 
    AzureWebApp(checkinCheckout1, "Check-in / Check-out", "API")
    AzureSqlDatabase(checkinCheckout2, "Database", "Sql Server")
    Rel_D(checkinCheckout1, checkinCheckout2, " ")
   }

   System_Boundary(notificacao1, "Notificacao - boundery context") {
    AzureWebApp(notificacao2, "Notificação", "API")
    System_Ext(notificacao3, "Twillo", "Mail marketing")
    System_Ext(notificacao4, "Disparopro", "SMS")
    AzureNotificationHubs(notificacao5, "push", "Azure Notification Hub")
    }        
   
}

Rel_D(cliente, pwa, "https")
Rel_D(pwa, api, "https")
Rel_L(api, catalogo2, "https")
Rel_D(api, checkinCheckout1, "https")
Rel_D(checkinCheckout1, pagamento2, "https")
Rel_D(checkinCheckout1, notificacao2, "https")
Rel_D(ecm2, notificacao2, "https")
Rel_D(api, ecm2, "https")

Rel_D(notificacao2, notificacao3, "https")
Rel_D(notificacao2, notificacao4, "https")
Rel_D(notificacao2, notificacao5, "https")

@enduml