@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(cliente, "Cliente", "Um cliente que deseja alugar ou devolver um veículo.")
System(pwa, "PWA", " ")
'System(site, "Site", " ")
System(api, "API Rest", "pool de api's")
System(catalogoApi, "Catálogo", "")
System(pagamentoApi, "Pagamento", "")
System(ECMApi, "ECM", "Engine Control Module")
System_Ext(botService, "Bot", "Bot do Azure")
System_Ext(pagamentoService, "Pagamento", "Mercado Pago")
System_Ext(CMSService, "CMS", "WordPress")
System_Ext(autenticacaoService, "Autenticação", "Azure AD B2C")
System_Ext(emailMarketingService, "E-mail Marketing", "Mailchimp")
System_Ext(googleMaps, "Google", "Maps")

Rel(cliente, pwa, " ")
'Rel(cliente, site, " ")
Rel(pwa, api, " ")
'Rel(site, api, " ")
Rel(api, catalogoApi, " ")
Rel(api, pagamentoApi, " ")
Rel(api, ECMApi, " ")
Rel(api, botService, " ")
Rel(pagamentoApi, pagamentoService, " ")
Rel(cliente, CMSService, " ")
Rel(cliente, autenticacaoService, " ")
Rel(emailMarketingService, cliente, " ")
Rel(ECMApi, googleMaps, " ")
@enduml

