@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(cl, "Cliente", "Usuário do sistema logado na aplicação PWA.")
System(cr, "Central de Requisiçoes", "Permite a interação para que os caros sejam liberados para uso, devolvidos, realização de checklist ou para sinalizar problemas durante o uso.")
'System_Ext(es, "E-mail system", "The internal Microsoft Exchange e-mail system.")
'System_Ext(mbs, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Rel(cl, cr, "item")
'Rel(es, pbc, "Sends e-mails to")
'Rel(ibs, es, "Sends e-mails", "SMTP")
'Rel(ibs, mbs, "Uses")
@enduml
