@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()

Person(cliente, "Cliente", "Um cliente que deseja alugar ou devolver um veículo.")
System(pwa, "PWA", " ")
System(site, "Site", " ")
System(api, "API Rest", " ")
System(catalogoApi, "Catálogo", "")
System(pagamentoApi, "Pagamento", "")
System_Ext(bot, "Bot", "Bot do Azure")
System_Ext(pagamentoService, "Pagamento", "Mercado Pago")
System_Ext(CMSService, "CMS", "Webflow")
System_Ext(autenticacaoService, "Autenticação", "Azure AD")
System_Ext(emailMarketingService, "E-mail Marketing", "Mailchimp")


Rel(cliente, pwa, " ")
Rel(cliente, site, " ")
Rel(pwa, api, " ")
Rel(site, api, " ")
Rel(api, catalogoApi, " ")
Rel(api, pagamentoApi, " ")
Rel(pagamentoApi, pagamentoService, " ")
Rel(CMSService, cliente, " ")
Rel(autenticacaoService, cliente, " ")
Rel(emailMarketingService, cliente, " ")
Rel(bot, cliente, " ")

@enduml

