@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml

LAYOUT_WITH_LEGEND()

System(pwa, "PWA", " ")
'System(site, "Site", " ")

System_Boundary(eeas, "EAS Eletric Auto Share") {
    System(api, "API Rest", "pool de api's")
    ContainerDb(apiCache, "Cache", " ", " ")
    System(catalogoApi, "Catálogo", "")
    System(notificacaoApi, "Notificação", "")
    System(CheckInCheckouApi, "Check-in / Check-out", "reserva com pre-autorização")
    System(ECMApi, "ECM", "")
    ContainerDb(ECMData, "No-SQL", " ", " ")
    ContainerDb(catalogoSQL, "SQL", " ", " ")
    System_Ext(CDNBlobImages, "CDN", " ")
    System(pagamentoApi, "Pagamento", "")
    ContainerDb(pagamentoSQL, "SQL", " ", " ")
}

Rel(pwa, api, "https")
Rel(api, apiCache, "tcp")
Rel(api, ECMApi, "https")
Rel(api, catalogoApi, "https")
Rel(catalogoApi, catalogoSQL, "tcp")
Rel(catalogoApi, CDNBlobImages, "https")
Rel(pagamentoApi, pagamentoSQL, "tcp")
Rel(pagamentoApi, CheckInCheckouApi, "tcp")
Rel(api, CheckInCheckouApi, "https")
Rel(ECMApi, ECMData, "tcp")
Rel(CheckInCheckouApi, notificacaoApi, "tcp")
Rel(ECMApi, notificacaoApi, "tcp")

@enduml