@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml

LAYOUT_WITH_LEGEND()

System(pwa, "PWA", " ")
System(site, "Site", " ")

System_Boundary(eeas, "EAS Eletric Auto Share") {
    System(api, "API Rest", " ")
    ContainerDb(apiCache, "Cache", " ", " ")
    System(catalogoApi, "Catálogo", "")
    ContainerDb(catalogoSQL, "SQL", " ", " ")
    ContainerDb(catalogoBlob, "Blob", " ", " ")
    System(pagamentoApi, "Pagamento", "")
    ContainerDb(pagamentoSQL, "SQL", " ", " ")
    'System_Ext(bot, "Bot", "Bot do Azure")
    'System_Ext(pagamentoService, "Pagamento", "Mercado Pago")
    'System_Ext(CMSService, "CMS", "Webflow")
    'System_Ext(autenticacaoService, "Autenticação", "Azure AD")
    'System_Ext(emailMarketingService, "E-mail Marketing", "Mailchimp")
}

Rel(pwa, api, " ")
Rel(site, api, " ")
Rel(api, apiCache, " ")
Rel(api, catalogoApi, " ")
Rel(catalogoApi, catalogoSQL, " ")
Rel(catalogoApi, catalogoBlob, " ")
Rel(api, pagamentoApi, " ")
Rel(pagamentoApi, pagamentoSQL, " ")

'Rel(pagamentoApi, pagamentoService, " ")
'Rel(CMSService, cliente, " ")
'Rel(autenticacaoService, cliente, " ")
'Rel(emailMarketingService, cliente, " ")
'Rel(bot, cliente, " ")

@enduml