@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml

LAYOUT_WITH_LEGEND()

System(pwa, "PWA", " ")
System_Ext(CDNBlobImages, "CDN", " ")

System_Boundary(eeas, "EAS Eletric Auto Share") {
    System(api, "API Rest", "pool de api's")
    ContainerDb(apiCache, "Cache", "No-SQL", " ")
    System(catalogoApi, "Catálogo", "")
    System(notificacaoApi, "Notificação", "")
    System(CheckInCheckouApi, "Check-in / Check-out", "reserva com pre-autorização")
    System(ECMApi, "ECM", "")
    ContainerDb(ECMData, "Database", "No-SQL", " ")
    ContainerDb(catalogoSQL, "Database", "No-SQL", "")    
    System(pagamentoApi, "Pagamento", "")
    ContainerDb(pagamentoSQL, "Database", "SQL", " ")
}

Rel(api, apiCache, "tcp")
Rel(api, ECMApi, "https")
Rel(api, catalogoApi, "https")
Rel(catalogoApi, catalogoSQL, "tcp")
Rel(pwa, CDNBlobImages, "https")
Rel(CDNBlobImages, api, "https")
Rel(pagamentoApi, pagamentoSQL, "tcp")
Rel(pagamentoApi, CheckInCheckouApi, "tcp")
Rel(api, CheckInCheckouApi, "https")
Rel(ECMApi, ECMData, "tcp")
Rel(CheckInCheckouApi, notificacaoApi, "tcp")
Rel(ECMApi, notificacaoApi, "tcp")

@enduml